架构不支持则退出

diff --git a/netease-cloud-music.SlackBuild b/netease-cloud-music.SlackBuild
--- a/netease-cloud-music.SlackBuild
+++ b/netease-cloud-music.SlackBuild
@@ -75,7 +75,8 @@ case $ARCH in
     )
     ;;
   *)
-    echo "Unsupport arch \"${ARCH}\""
+    echo "Error: Unsupport arch \"${ARCH}\"" >&2
+    exit 1
     ;;
 esac
 
